set_pin_physical_constraints -pin_name {DSM_EN} -offset 20 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[22]} -offset 21 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[21]} -offset 22 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[20]} -offset 23 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[19]} -offset 24 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[18]} -offset 25 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[17]} -offset 26 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[16]} -offset 27 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[15]} -offset 28 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[14]} -offset 29 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[13]} -offset 30 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[12]} -offset 31 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[11]} -offset 32 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[10]} -offset 33 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[9]} -offset 34 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[8]} -offset 35 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[7]} -offset 36 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[6]} -offset 37 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[5]} -offset 38 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[4]} -offset 39 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[3]} -offset 40 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[2]} -offset 41 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[1]} -offset 42 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_FOD[0]} -offset 43 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_EN} -offset 44 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_EN} -offset 45 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_MODE} -offset 46 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_KS[4]} -offset 47 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_KS[3]} -offset 48 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_KS[2]} -offset 49 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_KS[1]} -offset 50 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_C_KS[0]} -offset 51 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[9]} -offset 52 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[8]} -offset 53 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[7]} -offset 54 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[6]} -offset 55 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[5]} -offset 56 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[4]} -offset 57 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[3]} -offset 58 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[2]} -offset 59 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[1]} -offset 60 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PHASE_CTRL[0]} -offset 61 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_KS[4]} -offset 62 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_KS[3]} -offset 63 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_KS[2]} -offset 64 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_KS[1]} -offset 65 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PCALI_KS[0]} -offset 66 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DTC_EN} -offset 67 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {RT_EN} -offset 68 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DTCCALI_EN} -offset 69 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {OFSTCALI_EN} -offset 70 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PSEG[1]} -offset 71 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {PSEG[0]} -offset 72 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {CALIORDER[1]} -offset 73 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {CALIORDER[0]} -offset 74 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KB[4]} -offset 75 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KB[3]} -offset 76 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KB[2]} -offset 77 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KB[1]} -offset 78 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KB[0]} -offset 79 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KC[4]} -offset 80 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KC[3]} -offset 81 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KC[2]} -offset 82 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KC[1]} -offset 83 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KC[0]} -offset 84 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KD[4]} -offset 85 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KD[3]} -offset 86 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KD[2]} -offset 87 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KD[1]} -offset 88 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KD[0]} -offset 89 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[9]} -offset 90 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[8]} -offset 91 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[7]} -offset 92 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[6]} -offset 93 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[5]} -offset 94 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[4]} -offset 95 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[3]} -offset 96 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[2]} -offset 97 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[1]} -offset 98 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCB_INIT[0]} -offset 99 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[9]} -offset 100 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[8]} -offset 101 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[7]} -offset 102 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[6]} -offset 103 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[5]} -offset 104 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[4]} -offset 105 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[3]} -offset 106 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[2]} -offset 107 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[1]} -offset 108 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCC_INIT[0]} -offset 109 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[9]} -offset 110 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[8]} -offset 111 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[7]} -offset 112 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[6]} -offset 113 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[5]} -offset 114 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[4]} -offset 115 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[3]} -offset 116 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[2]} -offset 117 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[1]} -offset 118 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT0[0]} -offset 119 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[9]} -offset 120 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[8]} -offset 121 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[7]} -offset 122 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[6]} -offset 123 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[5]} -offset 124 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[4]} -offset 125 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[3]} -offset 126 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[2]} -offset 127 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[1]} -offset 128 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTCD_INIT1[0]} -offset 129 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_DN_EN} -offset 130 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_DN_WEIGHT[1]} -offset 131 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FCW_DN_WEIGHT[0]} -offset 132 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DSM_SYNC_NRST_EN} -offset 133 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {NCO_SYNC_NRST_EN} -offset 134 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {FREQ_HOP} -offset 135 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SECSEL_TEST[1]} -offset 136 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {SECSEL_TEST[0]} -offset 137 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {REGSEL_TEST[2]} -offset 138 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {REGSEL_TEST[1]} -offset 139 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {REGSEL_TEST[0]} -offset 140 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[9]} -offset 141 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[8]} -offset 142 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[7]} -offset 143 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[6]} -offset 144 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[5]} -offset 145 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[4]} -offset 146 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[3]} -offset 147 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[2]} -offset 148 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[1]} -offset 149 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {DPH_C_CUT[0]} -offset 150 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[10]} -offset 151 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[9]} -offset 152 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[8]} -offset 153 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[7]} -offset 154 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[6]} -offset 155 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[5]} -offset 156 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[4]} -offset 157 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[3]} -offset 158 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[2]} -offset 159 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[1]} -offset 160 -layers {M3} -width 0.3 -depth 0 -side 2
set_pin_physical_constraints -pin_name {LUT_INT[0]} -offset 161 -layers {M3} -width 0.3 -depth 0 -side 2


set_pin_physical_constraints -pin_name {MMD_DCW_X4[27]} -offset 12 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[20]} -offset 12.78 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[13]} -offset 13.56 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[6]} -offset 14.34 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[26]} -offset 15.77 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[19]} -offset 16.55 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[12]} -offset 17.33 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[5]} -offset 18.11 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[25]} -offset 19.54 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[18]} -offset 20.32 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[11]} -offset 21.1 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[4]} -offset 21.88 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[24]} -offset 23.31 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[17]} -offset 24.09 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[10]} -offset 24.87 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[3]} -offset 25.65 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[23]} -offset 27.08 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[16]} -offset 27.86 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[9]} -offset 28.64 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[2]} -offset 29.42 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[22]} -offset 30.85 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[15]} -offset 31.63 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[8]} -offset 32.41 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[1]} -offset 33.19 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[21]} -offset 34.62 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[14]} -offset 35.4 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[7]} -offset 36.18 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {MMD_DCW_X4[0]} -offset 36.96 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {RT_DCW_X4[3]} -offset 37.96 -layers {M5} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {RT_DCW_X4[2]} -offset 38.96 -layers {M5} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {RT_DCW_X4[1]} -offset 39.96 -layers {M5} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {RT_DCW_X4[0]} -offset 40.96 -layers {M5} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {CLK} -offset 66.5 -layers {M5} -width 0.3 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[0]} -offset 78.57 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[10]} -offset 79.35 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[20]} -offset 80.13 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[30]} -offset 80.91 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[1]} -offset 82.34 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[11]} -offset 83.12 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[21]} -offset 83.9 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[31]} -offset 84.68 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[2]} -offset 86.11 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[12]} -offset 86.89 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[22]} -offset 87.67 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[32]} -offset 88.45 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[3]} -offset 89.88 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[13]} -offset 90.66 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[23]} -offset 91.44 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[33]} -offset 92.22 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[4]} -offset 93.65 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[14]} -offset 94.43 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[24]} -offset 95.21 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[34]} -offset 95.99 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[5]} -offset 97.42 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[15]} -offset 98.2 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[25]} -offset 98.98 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[35]} -offset 99.76 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[6]} -offset 101.19 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[16]} -offset 101.97 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[26]} -offset 102.75 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[36]} -offset 103.53 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[7]} -offset 104.96 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[17]} -offset 105.74 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[27]} -offset 106.52 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[37]} -offset 107.3 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[8]} -offset 108.73 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[18]} -offset 109.51 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[28]} -offset 110.29 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[38]} -offset 111.07 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[9]} -offset 112.5 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[19]} -offset 113.28 -layers {M3} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[29]} -offset 114.06 -layers {M5} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCW_X4[39]} -offset 114.84 -layers {M5} -width 0.08 -depth 0 -side 4


set_pin_physical_constraints -pin_name {SYS_REF} -offset 30 -layers {M4} -width 0.3 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SYS_EN} -offset 31 -layers {M4} -width 0.3 -depth 0 -side 1
set_pin_physical_constraints -pin_name {NARST} -offset 32 -layers {M4} -width 0.3 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[11]} -offset 33 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[10]} -offset 34 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[9]} -offset 35 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[8]} -offset 36 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[7]} -offset 37 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[6]} -offset 38 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[5]} -offset 39 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[4]} -offset 40 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[3]} -offset 41 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[2]} -offset 42 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[1]} -offset 43 -layers {M3} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {PHE_X4[0]} -offset 44 -layers {M3} -width 0.11 -depth 0 -side 1
