
# left
set_pin_physical_constraints -pin_name {NARST} -offset 20 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CONFIGWIN} -offset 20.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[0]} -offset 21.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[1]} -offset 21.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[2]} -offset 22.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[3]} -offset 23 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[4]} -offset 23.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[5]} -offset 24.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[6]} -offset 24.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[7]} -offset 25.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[8]} -offset 26 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[9]} -offset 26.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[10]} -offset 27.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[11]} -offset 27.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[12]} -offset 28.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[13]} -offset 29 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[14]} -offset 29.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[15]} -offset 30.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[16]} -offset 30.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[17]} -offset 31.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[18]} -offset 32 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[19]} -offset 32.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[20]} -offset 33.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW1[21]} -offset 33.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[0]} -offset 34.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[1]} -offset 35 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[2]} -offset 35.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[3]} -offset 36.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[4]} -offset 36.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[5]} -offset 37.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[6]} -offset 38 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[7]} -offset 38.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[8]} -offset 39.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[9]} -offset 39.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[10]} -offset 40.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[11]} -offset 41 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[12]} -offset 41.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[13]} -offset 42.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[14]} -offset 42.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[15]} -offset 43.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[16]} -offset 44 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[17]} -offset 44.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[18]} -offset 45.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[19]} -offset 45.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[20]} -offset 46.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_FCW2[21]} -offset 47 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_EN} -offset 47.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTC_EN} -offset 48.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_GAC_EN} -offset 48.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DSM_EN} -offset 49.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_EN} -offset 50 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_IIR1EN} -offset 50.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_IIR2EN} -offset 51.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DSM1STEN} -offset 51.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DLFEN} -offset 52.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMD_SOR} -offset 53 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTC_SOR} -offset 53.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTWF_SOR} -offset 54.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[0]} -offset 54.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[1]} -offset 55.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[2]} -offset 56 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[3]} -offset 56.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[4]} -offset 57.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[5]} -offset 57.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_P[6]} -offset 58.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_MMDDCW_S} -offset 59 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[0]} -offset 59.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[1]} -offset 60.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[2]} -offset 60.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[3]} -offset 61.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[4]} -offset 62 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[5]} -offset 62.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[6]} -offset 63.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[7]} -offset 63.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[8]} -offset 64.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[9]} -offset 65 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[10]} -offset 65.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DTCDCW[11]} -offset 66.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[0]} -offset 66.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[1]} -offset 67.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[2]} -offset 68 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[3]} -offset 68.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[4]} -offset 69.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_C[5]} -offset 69.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[0]} -offset 70.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[1]} -offset 71 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[2]} -offset 71.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[3]} -offset 72.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[4]} -offset 72.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[5]} -offset 73.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_OTW_F[6]} -offset 74 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_CALIORDER[0]} -offset 74.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_CALIORDER[1]} -offset 75.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_CALIORDER[2]} -offset 75.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_PSEC[0]} -offset 76.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_PSEC[1]} -offset 77 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_PSEC[2]} -offset 77.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[0]} -offset 78.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[1]} -offset 78.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[2]} -offset 79.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[3]} -offset 80 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_WEIGHT[4]} -offset 80.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DSM_MODE[0]} -offset 81.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DSM_MODE[1]} -offset 81.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_MODE[0]} -offset 82.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_DN_MODE[1]} -offset 83 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[0]} -offset 83.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[1]} -offset 84.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[2]} -offset 84.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[3]} -offset 85.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[4]} -offset 86 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[5]} -offset 86.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[6]} -offset 87.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[7]} -offset 87.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[8]} -offset 88.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[9]} -offset 89 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[10]} -offset 89.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[11]} -offset 90.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCA_INIT[12]} -offset 90.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[0]} -offset 91.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[1]} -offset 92 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[2]} -offset 92.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[3]} -offset 93.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[4]} -offset 93.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[5]} -offset 94.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[6]} -offset 95 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[7]} -offset 95.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[8]} -offset 96.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[9]} -offset 96.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[10]} -offset 97.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[11]} -offset 98 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCB_INIT[12]} -offset 98.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[0]} -offset 99.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[1]} -offset 99.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[2]} -offset 100.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[3]} -offset 101 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[4]} -offset 101.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[5]} -offset 102.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[6]} -offset 102.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[7]} -offset 103.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[8]} -offset 104 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[9]} -offset 104.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[10]} -offset 105.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[11]} -offset 105.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KDTCC_INIT[12]} -offset 106.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA[0]} -offset 107 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA[1]} -offset 107.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA[2]} -offset 108.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA[3]} -offset 108.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA[4]} -offset 109.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB[0]} -offset 110 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB[1]} -offset 110.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB[2]} -offset 111.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB[3]} -offset 111.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB[4]} -offset 112.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC[0]} -offset 113 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC[1]} -offset 113.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC[2]} -offset 114.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC[3]} -offset 114.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC[4]} -offset 115.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[0]} -offset 116 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[1]} -offset 116.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[2]} -offset 117.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[3]} -offset 117.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[4]} -offset 118.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPS[5]} -offset 119 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[0]} -offset 119.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[1]} -offset 120.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[2]} -offset 120.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[3]} -offset 121.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[4]} -offset 122 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIS[5]} -offset 122.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[0]} -offset 123.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[1]} -offset 123.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[2]} -offset 124.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[3]} -offset 125 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[4]} -offset 125.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR1S[5]} -offset 126.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[0]} -offset 126.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[1]} -offset 127.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[2]} -offset 128 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[3]} -offset 128.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[4]} -offset 129.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KIIR2S[5]} -offset 129.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[0]} -offset 130.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_SECSEL_TEST[1]} -offset 131 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[0]} -offset 131.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[1]} -offset 132.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[2]} -offset 132.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_REGSEL_TEST[3]} -offset 133.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_PHASEC_EN} -offset 134 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_PHASE_DN_EN} -offset 134.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPHASE[0]} -offset 135.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPHASE[1]} -offset 135.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPHASE[2]} -offset 136.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPHASE[3]} -offset 137 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KPHASE[4]} -offset 137.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA_AUX[0]} -offset 138.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA_AUX[1]} -offset 138.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA_AUX[2]} -offset 139.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA_AUX[3]} -offset 140 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KA_AUX[4]} -offset 140.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB_AUX[0]} -offset 141.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB_AUX[1]} -offset 141.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB_AUX[2]} -offset 142.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB_AUX[3]} -offset 143 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KB_AUX[4]} -offset 143.6 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC_AUX[0]} -offset 144.2 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC_AUX[1]} -offset 144.8 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC_AUX[2]} -offset 145.4 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC_AUX[3]} -offset 146 -layers {M4} -width 0.11 -depth 0 -side 1
set_pin_physical_constraints -pin_name {SPI_KC_AUX[4]} -offset 146.6 -layers {M4} -width 0.11 -depth 0 -side 1

# top
set_pin_physical_constraints -pin_name {KDTC_TEST1[12]} -offset 20 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[11]} -offset 20.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[10]} -offset 21.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[9]} -offset 21.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[8]} -offset 22.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[7]} -offset 23 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[6]} -offset 23.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[5]} -offset 24.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[4]} -offset 24.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[3]} -offset 25.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[2]} -offset 26 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[1]} -offset 26.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST1[0]} -offset 27.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[12]} -offset 27.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[11]} -offset 28.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[10]} -offset 29 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[9]} -offset 29.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[8]} -offset 30.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[7]} -offset 30.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[6]} -offset 31.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[5]} -offset 32 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[4]} -offset 32.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[3]} -offset 33.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[2]} -offset 33.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[1]} -offset 34.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {KDTC_TEST2[0]} -offset 35 -layers {M3} -width 0.11 -depth 0 -side 2

# bottom
set_pin_physical_constraints -pin_name {O_DTCDCW1[11]} -offset 40 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[10]} -offset 40.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[9]} -offset 41.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[8]} -offset 41.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[7]} -offset 42.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[6]} -offset 43 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[5]} -offset 43.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[4]} -offset 44.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[3]} -offset 44.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[2]} -offset 45.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[1]} -offset 46 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW1[0]} -offset 46.6 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {REFMOD1} -offset 71.2 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {PDE1} -offset 76 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {REFMOD2} -offset 87.4 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {PDE2} -offset 91.6 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {O_MMDDCW_P1[6]} -offset 98.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[5]} -offset 98.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[4]} -offset 99.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[3]} -offset 100 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[2]} -offset 100.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[1]} -offset 101.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P1[0]} -offset 101.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[6]} -offset 102.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[5]} -offset 103 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[4]} -offset 103.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[3]} -offset 104.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[2]} -offset 104.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[1]} -offset 105.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_P2[0]} -offset 106 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[5]} -offset 106.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[4]} -offset 107.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[3]} -offset 107.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[2]} -offset 108.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[1]} -offset 109 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_C[0]} -offset 109.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[6]} -offset 110.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[5]} -offset 110.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[4]} -offset 111.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[3]} -offset 112 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[2]} -offset 112.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[1]} -offset 113.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_OTW_F[0]} -offset 113.8 -layers {M3} -width 0.11 -depth 0 -side 4

set_pin_physical_constraints -pin_name {O_DTCDCW2[11]} -offset 138.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[10]} -offset 139 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[9]} -offset 139.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[8]} -offset 140.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[7]} -offset 140.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[6]} -offset 141.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[5]} -offset 142 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[4]} -offset 142.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[3]} -offset 143.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[2]} -offset 143.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[1]} -offset 144.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_DTCDCW2[0]} -offset 145 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_S1} -offset 145.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {O_MMDDCW_S2} -offset 146.2 -layers {M3} -width 0.11 -depth 0 -side 4
