set_pin_physical_constraints -pin_name {IN[11]} -offset 30 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[10]} -offset 30.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[9]} -offset 31.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[8]} -offset 31.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[7]} -offset 32.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[6]} -offset 33 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[5]} -offset 33.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[4]} -offset 34.2 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[3]} -offset 34.8 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[2]} -offset 35.4 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[1]} -offset 36 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {IN[0]} -offset 36.6 -layers {M3} -width 0.11 -depth 0 -side 2
set_pin_physical_constraints -pin_name {NARST} -offset 45 -layers {M3} -width 0.11 -depth 0 -side 2


set_pin_physical_constraints -pin_name {CLK} -offset 6 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[11]} -offset 10 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[10]} -offset 10.6 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[9]} -offset 11.2 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[8]} -offset 11.8 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[7]} -offset 12.4 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[6]} -offset 13 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[5]} -offset 13.6 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[4]} -offset 14.2 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[3]} -offset 14.8 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[2]} -offset 15.4 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[1]} -offset 16 -layers {M4} -width 0.11 -depth 0 -side 3
set_pin_physical_constraints -pin_name {DTC_DCWTEST[0]} -offset 16.6 -layers {M4} -width 0.11 -depth 0 -side 3


set_pin_physical_constraints -pin_name {DTC_DCWMSBO[0]} -offset 4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[1]} -offset 4.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[2]} -offset 5.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[3]} -offset 5.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[4]} -offset 6.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[5]} -offset 7 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[6]} -offset 7.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[7]} -offset 8.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[8]} -offset 8.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[9]} -offset 9.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[10]} -offset 10 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[11]} -offset 10.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[12]} -offset 11.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[13]} -offset 11.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[14]} -offset 12.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[15]} -offset 13 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[16]} -offset 13.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[17]} -offset 14.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[18]} -offset 14.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[19]} -offset 15.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[20]} -offset 16 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[21]} -offset 16.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[22]} -offset 17.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[23]} -offset 17.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[24]} -offset 18.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[25]} -offset 19 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[26]} -offset 19.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[27]} -offset 20.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[28]} -offset 20.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[29]} -offset 21.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[30]} -offset 22 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[31]} -offset 22.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[32]} -offset 23.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[33]} -offset 23.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[34]} -offset 24.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[35]} -offset 25 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[36]} -offset 25.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[37]} -offset 26.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[38]} -offset 26.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[39]} -offset 27.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[40]} -offset 28 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[41]} -offset 28.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[42]} -offset 29.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[43]} -offset 29.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[44]} -offset 30.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[45]} -offset 31 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[46]} -offset 31.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[47]} -offset 32.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[48]} -offset 32.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[49]} -offset 33.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[50]} -offset 34 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[51]} -offset 34.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[52]} -offset 35.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[53]} -offset 35.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[54]} -offset 36.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[55]} -offset 37 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[56]} -offset 37.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[57]} -offset 38.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[58]} -offset 38.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[59]} -offset 39.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[60]} -offset 40 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[61]} -offset 40.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[62]} -offset 41.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWMSBO[63]} -offset 41.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[0]} -offset 42.4 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[1]} -offset 43 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[2]} -offset 43.6 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[3]} -offset 44.2 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[4]} -offset 44.8 -layers {M3} -width 0.11 -depth 0 -side 4
set_pin_physical_constraints -pin_name {DTC_DCWLSBO[5]} -offset 45.4 -layers {M3} -width 0.11 -depth 0 -side 4
